"""Load an exported HyperView bundle back into a live runtime.

``hyperview export`` writes a bundle: one folder that is the unit of delivery.
Hosting it as files on a static host makes it a **Static Space**. Loading it
here and serving it with ``hyperview serve --from <bundle>`` makes the same
folder a **Live Space** -- a real runtime with a dataset, embedding spaces,
layouts, collections, extensions, and the exported view already applied.

Restore is idempotent. Running it twice against the same
``HYPERVIEW_DATASETS_DIR`` reuses the dataset it finds instead of rebuilding
it, so a container that restarts comes back to the same Space rather than
re-ingesting on every boot. Reuse means the storage is kept, not that the
restore is skipped: rows, vectors, and coordinates are rewritten as upserts,
which is what keeps a restart correct after the bundle moves on disk or a newer
HyperView records a field the existing rows do not have.

A restored dataset owns its files. Media and extension folders are copied out
of the bundle into the restored dataset's own directory under
``HYPERVIEW_DATASETS_DIR`` (media goes to ``HYPERVIEW_MEDIA_DIR`` when that is
set), so deleting, moving, or re-exporting over the bundle afterwards cannot
break the dataset. ``link_media=True`` opts out and points at the bundle in
place; it is for a container that already owns the bundle for the life of the
process, such as the Live Space image generated by ``hyperview publish``.

Reuse never overwrites a good file. When a dataset of the same name is already
present, a sample keeps the ``filepath`` it has whenever that file exists and
lives outside the bundle -- the source dataset that produced the bundle is the
case that matters -- and only a missing file, or one that already points inside
the bundle, is re-pointed at the restored copy.
"""

from __future__ import annotations

import json
import mimetypes
import os
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from urllib.parse import quote

import numpy as np

from hyperview.core.dataset import Dataset
from hyperview.core.sample import Sample
from hyperview.extensions import EXTENSION_MANIFEST_NAME, resolve_panel_source
from hyperview.runtime import HyperViewRuntime, panel_payload_renders_module
from hyperview.static_export import (
    RESTORE_SCHEMA_VERSION,
    SAMPLE_MEDIA_FILENAME,
    read_bundle_manifest,
)
from hyperview.storage.config import StorageConfig

RESTORED_MEDIA_DIRNAME = "media"
RESTORED_EXTENSIONS_DIRNAME = "extensions"


@dataclass(frozen=True)
class BundleRestoreResult:
    """What a restore put into the runtime."""

    bundle_dir: Path
    workspace_id: str
    dataset_name: str
    num_samples: int
    num_spaces: int
    num_layouts: int
    num_collections: int
    num_extensions: int
    num_panels: int
    reused_dataset: bool
    link_media: bool = False
    media_dir: Path | None = None
    num_media_copied: int = 0
    num_media_linked: int = 0
    num_media_reused: int = 0
    warnings: tuple[str, ...] = ()

    def to_dict(self) -> dict[str, Any]:
        return {
            "bundle_dir": str(self.bundle_dir),
            "workspace_id": self.workspace_id,
            "dataset_name": self.dataset_name,
            "num_samples": self.num_samples,
            "num_spaces": self.num_spaces,
            "num_layouts": self.num_layouts,
            "num_collections": self.num_collections,
            "num_extensions": self.num_extensions,
            "num_panels": self.num_panels,
            "reused_dataset": self.reused_dataset,
            "link_media": self.link_media,
            "media_dir": str(self.media_dir) if self.media_dir is not None else None,
            "num_media_copied": self.num_media_copied,
            "num_media_linked": self.num_media_linked,
            "num_media_reused": self.num_media_reused,
            "warnings": list(self.warnings),
        }


def _read_json(path: Path) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except OSError as exc:
        raise RuntimeError(f"Bundle is missing {path.name}: {path}") from exc
    except json.JSONDecodeError as exc:
        raise RuntimeError(f"Bundle has invalid JSON at {path}: {exc}") from exc


def read_restore_manifest(bundle_dir: Path) -> dict[str, Any]:
    """Return the ``restore`` section of a bundle manifest.

    Bundles exported before restore existed are still valid Static Spaces, so
    the failure names what is missing rather than calling the folder invalid.
    """

    manifest = read_bundle_manifest(bundle_dir)
    restore = manifest.get("restore")
    if not isinstance(restore, dict) or restore.get("supported") is not True:
        raise RuntimeError(
            f"Bundle at {bundle_dir} carries no restore data and can only be hosted as a "
            "Static Space. Re-export it with this version of HyperView to run it as a "
            "Live Space."
        )
    schema_version = restore.get("schema_version")
    if schema_version != RESTORE_SCHEMA_VERSION:
        raise RuntimeError(
            f"Unsupported bundle restore schema_version {schema_version!r} "
            f"(this HyperView reads {RESTORE_SCHEMA_VERSION})"
        )
    return manifest


def _bundle_sample_payloads(bundle_dir: Path) -> list[dict[str, Any]]:
    """Read every sample record out of the bundle's sharded sample JSON."""

    samples_dir = bundle_dir / "api" / "samples"
    index = _read_json(samples_dir / "index.json")
    payloads: list[dict[str, Any]] = []
    for shard in index.get("shards") or []:
        if not isinstance(shard, dict) or not shard.get("path"):
            continue
        shard_payload = _read_json(samples_dir / str(shard["path"]))
        payloads.extend(
            item for item in (shard_payload.get("samples") or []) if isinstance(item, dict)
        )
    return payloads


def _sample_media_path(bundle_dir: Path, sample_id: str) -> Path:
    return bundle_dir / "api" / "samples" / quote(sample_id, safe="") / SAMPLE_MEDIA_FILENAME


def _safe_dataset_dirname(dataset_name: str) -> str:
    """A dataset name as one filesystem folder name.

    ``LanceDBBackend`` already stores a dataset under ``datasets_dir / name``,
    so an unslashed name -- every ordinary one -- lands beside its own storage.
    A slashed name is flattened rather than allowed to nest or escape.
    """

    return dataset_name.replace("/", "_").replace("\\", "_").strip() or "dataset"


def restored_media_dir(dataset_name: str) -> Path:
    """Where a restored dataset keeps its own copy of the bundle's media.

    The dataset must not depend on the bundle folder surviving, so the media
    lives with the dataset: under ``HYPERVIEW_MEDIA_DIR`` when the deployment
    sets one, and otherwise beside the dataset's own storage in
    ``HYPERVIEW_DATASETS_DIR``.
    """

    config = StorageConfig.default()
    folder = _safe_dataset_dirname(dataset_name)
    if os.environ.get("HYPERVIEW_MEDIA_DIR"):
        return config.media_dir / "restored" / folder
    return config.datasets_dir / folder / RESTORED_MEDIA_DIRNAME


def restored_extensions_dir(dataset_name: str) -> Path:
    """Where a restored dataset owns the extension folders the bundle carried."""

    return (
        StorageConfig.default().datasets_dir
        / _safe_dataset_dirname(dataset_name)
        / RESTORED_EXTENSIONS_DIRNAME
    )


def _is_inside(path: Path, root: Path) -> bool:
    try:
        resolved = path.expanduser().resolve()
    except OSError:
        return False
    return resolved == root or resolved.is_relative_to(root)


def _media_suffix(payload: dict[str, Any], media_type: str | None) -> str:
    """Recover a file extension for a bundle media copy.

    The bundle stores media extensionless under the sample id. The export kept
    the source ``filename``, which still carries a suffix; the recorded media
    type is the fallback.
    """

    filename = payload.get("filename")
    if filename:
        suffix = Path(str(filename)).suffix
        if suffix:
            return suffix
    if media_type:
        return mimetypes.guess_extension(str(media_type)) or ""
    return ""


def _copy_media_file(source: Path, target: Path) -> bool:
    """Copy one media file into the dataset's own directory.

    Returns whether bytes were written. ``copy2`` keeps the modification time,
    so a restart that restores an unchanged bundle rewrites nothing, while a
    re-exported bundle refreshes the copy the dataset owns.
    """

    target.parent.mkdir(parents=True, exist_ok=True)
    if target.is_file():
        source_stat = source.stat()
        target_stat = target.stat()
        if source_stat.st_size == target_stat.st_size and int(source_stat.st_mtime) == int(
            target_stat.st_mtime
        ):
            return False
    shutil.copy2(source, target)
    return True


def _sample_from_payload(
    bundle_dir: Path,
    payload: dict[str, Any],
    *,
    media_dir: Path,
    link_media: bool,
    existing: Sample | None,
) -> tuple[Sample, str]:
    """Rebuild one Sample and decide where its ``filepath`` should point.

    Four outcomes, returned as the second element:

    ``reused``
        The sample keeps the ``filepath`` it already had. Either the source
        dataset's own media in the case that matters -- a bundle restored on
        the machine that exported it -- or a copy this dataset already owns.
    ``copied``
        The sample was re-pointed at the restored dataset's own copy of the
        bundle's media, so the bundle can be deleted, moved, or re-exported
        without breaking the dataset.
    ``linked``
        ``link_media=True``: the sample points into the bundle in place. Only
        safe when the process owns the bundle for its whole life.
    ``missing``
        The bundle carries no media file for a sample that names one.
    """

    sample_id = str(payload["id"])

    # The bundle stores media under the sample id with no extension, so the
    # media type can no longer be guessed from the path. The export kept the
    # source `filename`, which still carries one; recover the type from there
    # when the source dataset did not record it.
    media_type = payload.get("media_type")
    if not media_type:
        filename = payload.get("filename")
        if filename:
            media_type = mimetypes.guess_type(str(filename))[0]

    target = media_dir / f"{quote(sample_id, safe='')}{_media_suffix(payload, media_type)}"
    current = existing.filepath if existing is not None else None
    filepath: str | None = None
    outcome = "none"
    if (
        current
        and not _is_inside(Path(current), bundle_dir)
        and Path(current) != target
        and Path(current).expanduser().is_file()
    ):
        # Never replace a valid file that lives outside the bundle. The one
        # path that is not left alone is this dataset's own copy, which the
        # copy below refreshes if -- and only if -- the bundle's bytes changed.
        filepath = current
        outcome = "reused"
    else:
        media_path = _sample_media_path(bundle_dir, sample_id)
        if media_path.is_file():
            if link_media:
                filepath = str(media_path)
                outcome = "linked"
            else:
                # Refreshes the copy this dataset owns when the bundle's bytes
                # changed, and writes nothing when they did not.
                _copy_media_file(media_path, target)
                filepath = str(target)
                outcome = "reused" if filepath == current else "copied"
        elif payload.get("media_url"):
            outcome = "missing"

    metadata = payload.get("metadata")
    return (
        Sample(
            id=sample_id,
            filepath=filepath,
            label=payload.get("label"),
            text=payload.get("text"),
            metadata=dict(metadata) if isinstance(metadata, dict) else {},
            width=payload.get("width"),
            height=payload.get("height"),
            media_type=media_type,
            duration_s=payload.get("duration_s"),
            modality=str(payload.get("modality") or "image"),
        ),
        outcome,
    )


@dataclass
class _MediaCounts:
    copied: int = 0
    linked: int = 0
    reused: int = 0


def _restore_dataset(
    bundle_dir: Path,
    dataset_name: str,
    dataset_payload: dict[str, Any],
    *,
    link_media: bool,
) -> tuple[Dataset, int, bool, _MediaCounts, list[str]]:
    payloads = _bundle_sample_payloads(bundle_dir)

    dataset = Dataset(dataset_name)
    existing = {item.id: item for item in dataset.samples}
    media_dir = restored_media_dir(dataset_name)

    samples: list[Sample] = []
    missing_media: list[str] = []
    counts = _MediaCounts()
    for payload in payloads:
        sample, outcome = _sample_from_payload(
            bundle_dir,
            payload,
            media_dir=media_dir,
            link_media=link_media,
            existing=existing.get(str(payload["id"])),
        )
        samples.append(sample)
        if outcome == "missing":
            missing_media.append(sample.id)
        elif outcome == "copied":
            counts.copied += 1
        elif outcome == "linked":
            counts.linked += 1
        elif outcome == "reused":
            counts.reused += 1

    already_restored = bool(existing) and set(existing) == {item.id for item in samples}

    # The dataset is reused rather than rebuilt, but its sample rows are always
    # rewritten from the bundle. The rows are an upsert of already-decoded
    # records -- no media decoding, no downloads -- so this costs a fraction of
    # ingestion, and it is what keeps a restart correct when the bundle has
    # moved on disk or a newer HyperView records a field the old rows lack.
    # `filepath` is the one field a reused row can keep, decided above.
    dataset.add_samples(samples, skip_existing=False)

    fields = dataset_payload.get("fields")
    if isinstance(fields, dict) and fields:
        dataset._storage.register_fields(fields)

    warnings: list[str] = []
    if missing_media:
        preview = ", ".join(missing_media[:5])
        suffix = "" if len(missing_media) <= 5 else f", and {len(missing_media) - 5} more"
        warnings.append(
            f"{len(missing_media)} samples reference media the bundle does not carry "
            f"({preview}{suffix}); they were restored without a media file."
        )

    return dataset, len(samples), already_restored, counts, warnings


def _restore_spaces(bundle_dir: Path, dataset: Dataset, restore: dict[str, Any]) -> int:
    """Recreate embedding spaces under their source space ids.

    The space id is not cosmetic: index ids (``space:<space_key>``), layout
    rows, collection queries, and panel props all address it, so a restored
    space that picked a fresh key would leave the exported view pointing at
    nothing.
    """

    entries = [item for item in (restore.get("spaces") or []) if isinstance(item, dict)]
    for entry in entries:
        vectors_ref = entry.get("vectors")
        if not vectors_ref:
            continue
        with np.load(bundle_dir / str(vectors_ref), allow_pickle=False) as payload:
            ids = [str(item) for item in payload["ids"].tolist()]
            vectors = np.asarray(payload["vectors"], dtype=np.float32)
        dataset.register_embeddings(
            str(entry["space_key"]),
            str(entry.get("model_id") or entry["space_key"]),
            ids,
            vectors,
            config=entry.get("config"),
        )
    return len(entries)


def _restore_layouts(bundle_dir: Path, dataset: Dataset, restore: dict[str, Any]) -> int:
    """Recreate layouts under their source layout keys."""

    entries = [item for item in (restore.get("layouts") or []) if isinstance(item, dict)]
    for entry in entries:
        coords_ref = entry.get("coords")
        if not coords_ref:
            continue
        payload = _read_json(bundle_dir / str(coords_ref))
        ids = [str(item) for item in (payload.get("ids") or [])]
        coords = np.asarray(payload.get("coords") or [], dtype=np.float32)
        if not ids:
            continue
        dataset.register_layout(
            str(entry["layout_key"]),
            str(entry["space_key"]),
            ids,
            coords,
            method=str(entry.get("method") or "precomputed"),
            geometry=str(entry.get("geometry") or "euclidean"),
            params=entry.get("params"),
        )
    return len(entries)


def _own_extension_folder(source: Path, target: Path) -> Path:
    """Copy one extension folder out of the bundle and return the owned copy."""

    resolved_source = source.resolve()
    if target.exists():
        if target.resolve() == resolved_source:
            # Someone restored a bundle that already lives here.
            return target
        shutil.rmtree(target)
    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copytree(
        resolved_source,
        target,
        ignore=shutil.ignore_patterns("__pycache__", "*.pyc", ".git"),
    )
    return target


def _install_bundle_extensions(
    bundle_dir: Path,
    runtime: HyperViewRuntime,
    workspace_id: str,
    restore: dict[str, Any],
    *,
    dataset_name: str,
    link_media: bool,
) -> tuple[int, list[str]]:
    """Install each extension the bundle carries through the normal path.

    The installed extension keeps pointing at the folder it was installed
    from -- panel modules and Python tools are read from there for the life of
    the Space -- so the folder is copied out of the bundle into the restored
    dataset's own ``extensions/`` directory first. ``link_media=True`` installs
    from the bundle in place, for a container that owns the bundle.

    ``add_panels`` is off: the exported workspace snapshot already describes
    every panel instance with its position, props, and state, and is applied
    afterwards. Letting the installer add its manifest defaults first would
    place panels the snapshot then has to overwrite.
    """

    installed = 0
    warnings: list[str] = []
    extensions_root = restored_extensions_dir(dataset_name)
    for entry in restore.get("extensions") or []:
        if not isinstance(entry, dict) or not entry.get("path"):
            continue
        name = str(entry.get("name") or entry["path"])
        folder = bundle_dir / str(entry["path"])
        if not (folder / EXTENSION_MANIFEST_NAME).is_file():
            warnings.append(
                f"Extension '{name}' is listed in the bundle manifest but its folder is "
                f"missing {EXTENSION_MANIFEST_NAME}; its panels and tools were not restored."
            )
            continue
        if not link_media:
            try:
                folder = _own_extension_folder(folder, extensions_root / _safe_dataset_dirname(name))
            except OSError as exc:
                warnings.append(
                    f"Extension '{name}' could not be copied out of the bundle ({exc}); "
                    "its panels and tools were not restored."
                )
                continue
        source = entry.get("source")
        try:
            runtime.install_extension(
                workspace_id,
                folder,
                add_panels=False,
                source="shipped" if source == "shipped" else "extension",
            )
        except Exception as exc:  # noqa: BLE001 - one bad extension must not sink the Space
            warnings.append(f"Extension '{name}' failed to install from the bundle: {exc}")
            continue
        installed += 1
    return installed, warnings


def _repair_panel_module_file(
    panel: dict[str, Any],
    runtime: HyperViewRuntime,
) -> str | None:
    """Re-point a panel at its module source on this host.

    The export strips ``module_file`` from the snapshot because it is a path on
    the machine that did the exporting. After the extensions are installed the
    real path is knowable again, and it has to be filled in before the payload
    is parsed: ``WorkspaceUiState.from_dict`` drops a module panel that has no
    module file, which would silently delete the panel from the restored view.
    """

    if panel.get("module_file"):
        return None
    if not panel_payload_renders_module(panel):
        return None

    panel_id = str(panel.get("id") or "?")
    extension = panel.get("extension")
    extension_panel = panel.get("extension_panel")
    if not extension or not extension_panel:
        return (
            f"Panel '{panel_id}' has no extension reference and no module source; "
            "it was dropped from the restored view."
        )

    installation = runtime.get_extension(str(extension))
    if installation is None:
        return (
            f"Panel '{panel_id}' needs extension '{extension}', which the bundle did not "
            "install; it was dropped from the restored view."
        )

    entry = next(
        (item for item in installation.manifest.panels if item.id == str(extension_panel)),
        None,
    )
    module_name = entry.module_file() if entry is not None else None
    if module_name is None:
        return (
            f"Panel '{panel_id}' is not declared by extension '{extension}'; "
            "it was dropped from the restored view."
        )

    try:
        panel["module_file"] = str(resolve_panel_source(installation.manifest.folder, module_name))
    except (FileNotFoundError, ValueError) as exc:
        return f"Panel '{panel_id}' module source could not be resolved: {exc}"
    return None


def _workspace_payload(
    snapshot: dict[str, Any],
    runtime: HyperViewRuntime,
    *,
    workspace_id: str,
    dataset_name: str,
) -> tuple[dict[str, Any], list[str]]:
    raw = snapshot.get("workspace")
    if not isinstance(raw, dict):
        raise RuntimeError("Bundle runtime snapshot has no workspace section")

    payload = json.loads(json.dumps(raw))
    payload["id"] = workspace_id
    payload["dataset_name"] = dataset_name

    warnings: list[str] = []
    ui = payload.get("ui")
    if isinstance(ui, dict):
        for panel in ui.get("custom_panels") or []:
            if not isinstance(panel, dict):
                continue
            # Static-hosting annotations (`static_compatible`, `module_src`)
            # describe the browser-only bundle and mean nothing to a runtime.
            panel.pop("data", None)
            warning = _repair_panel_module_file(panel, runtime)
            if warning is not None:
                warnings.append(warning)
    return payload, warnings


def restore_bundle(
    bundle: str | Path,
    *,
    runtime: HyperViewRuntime | None = None,
    workspace_id: str | None = None,
    link_media: bool = False,
) -> tuple[HyperViewRuntime, BundleRestoreResult]:
    """Restore a bundle into a runtime and return both.

    Args:
        bundle: Path to a folder written by ``hyperview export``.
        runtime: Runtime to restore into. A new one is created when omitted.
        workspace_id: Workspace id to restore under. Defaults to the id the
            bundle was exported from, which is what panel props and pinned
            layout keys expect.
        link_media: Point the restored dataset at the bundle's own media and
            extension folders instead of copying them into the datasets
            directory. Zero copies, and the dataset then depends on the bundle
            staying exactly where it is: only pass it when the process owns the
            bundle for its whole life, as the generated Live Space image does.

    Returns:
        ``(runtime, result)``.
    """

    bundle_dir = Path(bundle).expanduser().resolve()
    manifest = read_restore_manifest(bundle_dir)
    restore = manifest["restore"]

    dataset_name = str(manifest["workspace"].get("dataset_name") or "").strip()
    if not dataset_name:
        raise RuntimeError(f"Bundle manifest names no dataset: {bundle_dir}")

    target_workspace_id = str(workspace_id or manifest["workspace"]["id"]).strip()
    if not target_workspace_id:
        raise ValueError("workspace_id must be a non-empty string")

    snapshot = _read_json(bundle_dir / "api" / "runtime.json")
    dataset_payload = _read_json(bundle_dir / "api" / "dataset.json")

    runtime = runtime or HyperViewRuntime()
    runtime.workspace_registry.ensure_workspace(target_workspace_id, activate=True)

    dataset, num_samples, reused_dataset, media_counts, warnings = _restore_dataset(
        bundle_dir, dataset_name, dataset_payload, link_media=link_media
    )
    num_spaces = _restore_spaces(bundle_dir, dataset, restore)
    num_layouts = _restore_layouts(bundle_dir, dataset, restore)

    # Attach before applying the view: attaching a different dataset name
    # resets the workspace's collections, panel state, and active layout.
    runtime.attach_dataset_instance(target_workspace_id, dataset, activate_workspace=True)

    num_extensions, extension_warnings = _install_bundle_extensions(
        bundle_dir,
        runtime,
        target_workspace_id,
        restore,
        dataset_name=dataset_name,
        link_media=link_media,
    )
    warnings.extend(extension_warnings)

    payload, panel_warnings = _workspace_payload(
        snapshot,
        runtime,
        workspace_id=target_workspace_id,
        dataset_name=dataset_name,
    )
    warnings.extend(panel_warnings)
    workspace = runtime.restore_workspace_state(target_workspace_id, payload)

    return runtime, BundleRestoreResult(
        bundle_dir=bundle_dir,
        workspace_id=target_workspace_id,
        dataset_name=dataset_name,
        num_samples=num_samples,
        num_spaces=num_spaces,
        num_layouts=num_layouts,
        num_collections=len(workspace.collections),
        num_extensions=num_extensions,
        num_panels=len(workspace.ui.custom_panels),
        reused_dataset=reused_dataset,
        link_media=link_media,
        media_dir=None if link_media else restored_media_dir(dataset_name),
        num_media_copied=media_counts.copied,
        num_media_linked=media_counts.linked,
        num_media_reused=media_counts.reused,
        warnings=tuple(warnings),
    )


__all__ = [
    "BundleRestoreResult",
    "read_restore_manifest",
    "restore_bundle",
    "restored_extensions_dir",
    "restored_media_dir",
]
