#!/usr/bin/env python3
"""Emit the hosting-mode capability table into the frontend.

`hyperview.capabilities` is the only definition of what a Live Space and a
Static Space let a viewer do. The frontend needs the same table before it has
fetched a manifest (or on a live server, before `/api/capabilities` answers),
so this script writes it into `frontend/src/generated/capabilities.ts` rather
than letting TypeScript keep a hand-maintained second copy.

Run it after changing the table:

    python scripts/emit_capabilities_surface.py

tests/test_capabilities_contract.py fails when the committed file is stale.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from hyperview.capabilities import capability_surface  # noqa: E402

GENERATED_PATH = ROOT / "frontend" / "src" / "generated" / "capabilities.ts"

_HEADER = """// Generated by scripts/emit_capabilities_surface.py. Do not edit.
//
// The hosting-mode capability table from src/hyperview/capabilities.py. A
// Static Space narrows this with its manifest and a live server with
// GET /api/capabilities; this file is what the shell knows before either
// answers, and it is the only place TypeScript names a viewer command.

export type HostingMode = "live" | "static";

export interface ViewerCommandSurface {
  /** Command ids a viewer may run in this mode. */
  allowed: string[];
  /** Command-id prefixes a viewer may run in this mode. */
  allowed_prefixes: string[];
  /** Commands whose target carries an optional `panel_id`. */
  panel_target: string[];
}

export interface Capabilities {
  mode: HostingMode;
  browse_samples: boolean;
  layouts: boolean;
  selection: boolean;
  lasso_2d: boolean;
  lasso_3d: boolean;
  sample_similarity: boolean;
  similarity_k: number;
  text_search: boolean;
  new_layouts: boolean;
  python_tools: boolean;
  runtime_mutations: boolean;
  server_runtime: boolean;
  panel_state: "durable" | "ephemeral";
  commands: ViewerCommandSurface;
  /** Panel-by-panel export status; a Static Space manifest fills this in. */
  panels?: unknown[];
  /** Whether a live server is running without a session token. */
  public?: boolean;
}

export const CAPABILITY_MODES: Record<HostingMode, Capabilities> = """


def render(indent: int = 2) -> str:
    """Return the TypeScript module for the current table."""

    modes = capability_surface()["modes"]
    body = json.dumps(modes, indent=indent, sort_keys=True)
    return f"{_HEADER}{body};\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of writing when the committed file is stale",
    )
    args = parser.parse_args(argv)

    payload = render()
    if args.check:
        current = GENERATED_PATH.read_text(encoding="utf-8") if GENERATED_PATH.is_file() else ""
        if current != payload:
            print(f"{GENERATED_PATH} is stale; run python scripts/emit_capabilities_surface.py")
            return 1
        print(f"{GENERATED_PATH} is up to date")
        return 0

    GENERATED_PATH.parent.mkdir(parents=True, exist_ok=True)
    GENERATED_PATH.write_text(payload, encoding="utf-8")
    print(f"wrote {GENERATED_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
